name: 'Mise update by tool'
description: 'Workflow to create PR for updating mise config files one tool by one tool'
on:
  workflow_dispatch:
    inputs:
      mise_install_debug:
        description: "Active debug mode"
        default: "info"
        type: choice
        options:
          - "info"
          - "debug"
      get_mise_doctor_outputs:
        description: "Get mise doctor outputs"
        default: false
        type: boolean

jobs:
    list_tools:
      outputs:
        mise_json_matrix: ${{ steps.get-tool-to-update-json-format.outputs.mise_json }}
      runs-on: [ubuntu-22.04]
      steps:
        - name: "Checkout"
          uses: actions/checkout@v4

        - name: "Install mise tool"
          uses: jdx/mise-action@v2
          with:
            # version: 2024.10.0 # [default: latest] mise version to install
            install: false # No need to install tools to get information
            #install_args: "bun" # [default: ""] additional arguments to `mise install`
            cache: true # [default: true] cache mise using GitHub's cache
            experimental: true # [default: false] enable experimental features
            log_level: ${{ inputs.mise_install_debug }} # [default: info] log level

        - name: "Get mise doctor informations"
          if: ${{ inputs.get_mise_doctor_outputs }}
          shell: bash
          run: |
            mise doctor

        - name: Get List Tool To Update in Json Format
          id: get-tool-to-update-json-format
          shell: bash
          run: |
            echo "mise_json=$(mise outdated -l --json | jq -c -M 'map(select(.bump!=null))|{"include": .}')" >> ${GITHUB_OUTPUT}

    update_tool:
      runs-on: ubuntu-22.04
      needs: list_tools
      strategy:
        matrix: ${{ fromJSON(needs.list_tools.outputs.mise_json_matrix) }}
        fail-fast: false
      permissions:
          contents: write
          pull-requests: write
      steps:
        - name: "Checkout"
          uses: actions/checkout@v4

        - name: "Install mise tool"
          uses: jdx/mise-action@v2
          with:
            # version: 2024.10.0 # [default: latest] mise version to install
            install: false # No need to install tools to get information
            #install_args: "bun" # [default: ""] additional arguments to `mise install`
            cache: true # [default: true] cache mise using GitHub's cache
            experimental: true # [default: false] enable experimental features
            log_level: ${{ inputs.mise_install_debug }} # [default: info] log level

        - name: "Update tool ${{ matrix.name }}"
          shell: bash
          run: |
            mise upgrade --bump ${{ matrix.name }}

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v7
          with:
            commit-message: "chore(tools): update mise tool ${{ matrix.name }}"
            author: "Jean-Yves LENHOF <jygithub@lenhof.eu.org>"
            committer: "Jean-Yves LENHOF <jygithub@lenhof.eu.org>"
            token: "${{ secrets.GITHUB_TOKEN }}"
            branch: "chore/update_tool_${{ matrix.name }}"
            delete-branch: true
            draft: true
            title: "chore(tools): update mise tool ${{ matrix.name }}"
            body: |
              automated PR with complete
              description to do
