name: 'Mise update by tool'
description: 'Action to create PR for updating mise config files one tool by one tool'
on:
  workflow_dispatch:
    inputs:
      mise_install_debug:
        description: "Active debug mode"
        default: "info"
        type: choice
        options:
          - "info"
          - "debug"
      get_mise_doctor_outputs:
        description: "Get mise doctor outputs"
        default: false
        type: boolean

jobs:
    updater_tool:
      outputs:
        mise_json_matrix: ${{ steps.get-tool-to-update-json-format.outputs.mise_json }}
      runs-on: [ubuntu-22.04]
      steps:
        - name: "Checkout"
          uses: actions/checkout@v4

        - name: "Install mise tool"
          uses: jdx/mise-action@v2
          with:
            # version: 2024.10.0 # [default: latest] mise version to install
            install: false # No need to install tools to get information
            #install_args: "bun" # [default: ""] additional arguments to `mise install`
            cache: true # [default: true] cache mise using GitHub's cache
            experimental: true # [default: false] enable experimental features
            log_level: ${{ inputs.mise_install_debug }} # [default: info] log level

        - name: "Get mise doctor informations"
          if: ${{ inputs.get_mise_doctor_outputs }}
          shell: bash
          run: |
            mise doctor

        - name: Get List Tool To Update in Json Format
          id: get-tool-to-update-json-format
          shell: bash
          run: |
            echo "mise_json=$(mise outdated -l --json | jq -c -M)" >> ${GITHUB_OUTPUT}
    step2:
      runs-on: ubuntu-22.04
      needs: updater_tool
      # strategy:
      #   matrix:
      #     mise_json: ${{ fromJSON(needs.updater_tool.outputs.mise_json_matrix) }}
      #   fail-fast: false
      steps:
        - name: "Step 2 - 1"
          shell: bash
          run: |
            # echo ${{ matrix.mise_json }}
            echo ${{ needs.updater_tool.outputs.mise_json_matrix }}

