name: 'Mise update by tool'
description: 'Action to create PR for updating mise config files one tool by one tool'
on:
  workflow_dispatch:
jobs:
    updater_tool:  
      runs-on: [ubuntu-22.04]
      steps:
        - name: "Checkout"
          uses: actions/checkout@v4

        - name: "Install mise tool"
          uses: jdx/mise-action@v2
          with:
            # version: 2024.10.0 # [default: latest] mise version to install
            install: false # We need tools installed to get mise outdated works
            #install_args: "bun" # [default: ""] additional arguments to `mise install`
            cache: true # [default: true] cache mise using GitHub's cache
            experimental: true # [default: false] enable experimental features
            log_level: debug # [default: info] log level

        - name: Get List Tool To Update in Json Format
          id: get-tool-to-update-json-format
          shell: bash
          run: |
              mise doctor
              echo "mise_json=$(mise outdated -l --json | jq -c -M)" # >> ${GITHUB_OUTPUT}

